/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafos;

import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author criss
 */
public class FramePrincipal extends javax.swing.JFrame {
   Grafo grafo = new Grafo();
   Vertice verticeInicio;
   Vertice verticeFinal;
   int x, y;
   /**
    * Creates new form FramePrincipal
    */
   public FramePrincipal() {
      initComponents();
      jcbDepartamentoOrigen.setEnabled(false);
      jcbDepartamentoDestino.setEnabled(false);
      Image img = new ImageIcon("src/Img/BaseMap.png").getImage();
      Image image = img.getScaledInstance(jlbMapa.getWidth(), -1, Image.SCALE_SMOOTH);
      jlbMapa.setIcon(new ImageIcon(image));   
      
      grafo = new MapLoader().loadMapaGrafo();
      agregarItems();

      jcbDepartamentoOrigen.setSelectedIndex(-1);
      jcbDepartamentoDestino.setSelectedIndex(-1);
   }
   
   private void agregarItems()
   {
      for (Vertice v:grafo.getListaVertices())
      {
         if (!v.getType().equals("intercepcion")){
            jcbDepartamentoOrigen.addItem(v.getDato());
            jcbDepartamentoDestino.addItem(v.getDato());
         }
      }
   }
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jpMenu = new javax.swing.JPanel();
        jbtMostrarRutas = new javax.swing.JButton();
        jcbDepartamentoOrigen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbtCalcularRuta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbDepartamentoDestino = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResultados = new javax.swing.JTextArea();
        jpMapa = new javax.swing.JPanel();
        jlbMapa = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        jlbCerrar = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);

        jpMenu.setBackground(new java.awt.Color(51, 51, 51));

        jbtMostrarRutas.setBackground(new java.awt.Color(255, 255, 255));
        jbtMostrarRutas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtMostrarRutas.setText("MOSTRAR RUTAS");
        jbtMostrarRutas.setBorder(null);
        jbtMostrarRutas.setFocusPainted(false);
        jbtMostrarRutas.setFocusable(false);
        jbtMostrarRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMostrarRutasActionPerformed(evt);
            }
        });

        jcbDepartamentoOrigen.setBackground(new java.awt.Color(102, 102, 102));
        jcbDepartamentoOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbDepartamentoOrigen.setForeground(new java.awt.Color(255, 255, 255));
        jcbDepartamentoOrigen.setAutoscrolls(true);
        jcbDepartamentoOrigen.setFocusable(false);
        jcbDepartamentoOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDepartamentoOrigenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RUTA MÁS CORTA");

        jbtCalcularRuta.setBackground(new java.awt.Color(255, 255, 255));
        jbtCalcularRuta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtCalcularRuta.setText("CALCULAR RUTA");
        jbtCalcularRuta.setBorder(null);
        jbtCalcularRuta.setFocusPainted(false);
        jbtCalcularRuta.setFocusable(false);
        jbtCalcularRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalcularRutaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DEPARTAMENTO ORIGEN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DEPARTAMENTO DESTINO");

        jcbDepartamentoDestino.setBackground(new java.awt.Color(102, 102, 102));
        jcbDepartamentoDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbDepartamentoDestino.setForeground(new java.awt.Color(255, 255, 255));
        jcbDepartamentoDestino.setAutoscrolls(true);
        jcbDepartamentoDestino.setFocusable(false);
        jcbDepartamentoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDepartamentoDestinoActionPerformed(evt);
            }
        });

        jtResultados.setEditable(false);
        jtResultados.setBackground(new java.awt.Color(51, 51, 51));
        jtResultados.setColumns(20);
        jtResultados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtResultados.setForeground(new java.awt.Color(255, 255, 255));
        jtResultados.setLineWrap(true);
        jtResultados.setRows(5);
        jtResultados.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtResultados);

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbDepartamentoOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbDepartamentoDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jbtMostrarRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtCalcularRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbDepartamentoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jcbDepartamentoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtMostrarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCalcularRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpMapa.setBackground(new java.awt.Color(102, 153, 255));
        jpMapa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpMapaLayout = new javax.swing.GroupLayout(jpMapa);
        jpMapa.setLayout(jpMapaLayout);
        jpMapaLayout.setHorizontalGroup(
            jpMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMapaLayout.createSequentialGroup()
                .addComponent(jlbMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpMapaLayout.setVerticalGroup(
            jpMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMapaLayout.createSequentialGroup()
                .addComponent(jlbMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Panel.setBackground(new java.awt.Color(51, 51, 51));
        Panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelMouseDragged(evt);
            }
        });
        Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelMousePressed(evt);
            }
        });

        jlbCerrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlbCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jlbCerrar.setText("X");
        jlbCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbCerrar)
                .addGap(14, 14, 14))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCerrar)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   private void jbtMostrarRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMostrarRutasActionPerformed
      // TODO add your handling code here:
      if(jbtMostrarRutas.getText().equals("MOSTRAR RUTAS"))
      {
         verticeInicio = null;
         verticeFinal = null;
         jcbDepartamentoOrigen.setEnabled(true);
         jcbDepartamentoDestino.setEnabled(true);
         DibujarRutas.dibujarRutas(jpMapa.getGraphics(), grafo);
         jbtMostrarRutas.setText("OCULTAR RUTAS");
      }
      else
      {
         jpMapa.repaint();
         jbtMostrarRutas.setText("MOSTRAR RUTAS");
         jtResultados.setText("");
         jcbDepartamentoOrigen.setEnabled(false);
         jcbDepartamentoDestino.setEnabled(false);
         jcbDepartamentoOrigen.setSelectedIndex(-1);
         jcbDepartamentoDestino.setSelectedIndex(-1);
      }
   }//GEN-LAST:event_jbtMostrarRutasActionPerformed

   private void jbtCalcularRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalcularRutaActionPerformed
      // TODO add your handling code here:
      if (jcbDepartamentoOrigen.getSelectedIndex() != -1 && jcbDepartamentoDestino.getSelectedIndex() != -1)
      {
         Grafo Ruta = AlgoritmoDijkstra.obtenerRuta(grafo, verticeInicio, verticeFinal);
         List<Vertice> vertices = Ruta.getListaVertices();
         double DistanciaTotal = 0;
         Vertice lastVertice = null;
         
         //Algoritmo que calcula la distancia total de los segmentos del grafo.
         for (int i = 0; i < vertices.size(); i++)
         {
             if (lastVertice == null){
                 lastVertice = vertices.get(i);
             }
             else {
                 List<Arista> aristas = vertices.get(i).getAristas();
                 for (Arista arista : aristas){
                          
                    int id = vertices.get(i).getId();
                    int expectedId = lastVertice.getId();
                    int actualId = arista.getSegundoVertice(id);
                    if(actualId == expectedId){
                        DistanciaTotal += arista.getPeso();
                    }
                 }
                 lastVertice = vertices.get(i);
             }
         }
         
         DibujarRutas.dibujarRutas(jpMapa.getGraphics(), grafo);
         DibujarRutas.dibujarRutaMinima(jpMapa.getGraphics(), Ruta);
         
         //TODO: hacer un reporte mas completo.
         jtResultados.setText("Distancia Minima: " + String.format("%.2f", DistanciaTotal) + " Km\n");
      }
      else
      {
         JOptionPane.showMessageDialog(null, "Seleccione Un Departamento De Las Listas", "", JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_jbtCalcularRutaActionPerformed
/**/
   private void jlbCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCerrarMouseClicked
      System.exit(0);
   }//GEN-LAST:event_jlbCerrarMouseClicked

   private void PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMousePressed
      x = evt.getX();
      y = evt.getY();
   }//GEN-LAST:event_PanelMousePressed

   private void PanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMouseDragged
      this.setLocation(evt.getX() + this.getLocation().x - x, evt.getY() + this.getLocation().y - y);
   }//GEN-LAST:event_PanelMouseDragged

   private void jcbDepartamentoOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDepartamentoOrigenActionPerformed
      // TODO add your handling code here:
      if (jcbDepartamentoOrigen.isEnabled())
      {
         if (verticeInicio != null && verticeFinal != null)
         {
            if (verticeInicio != verticeFinal)
               DibujarRutas.deseleccionarVertice(jpMapa.getGraphics(), verticeInicio);
         }
         else
         {
            if (verticeInicio != null)
               DibujarRutas.deseleccionarVertice(jpMapa.getGraphics(), verticeInicio);
         }
         
         verticeInicio = grafo.buscarVertice(jcbDepartamentoOrigen.getSelectedItem().toString());
         DibujarRutas.seleccionarVertice(jpMapa.getGraphics(), verticeInicio);
      }
   }//GEN-LAST:event_jcbDepartamentoOrigenActionPerformed

   private void jcbDepartamentoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDepartamentoDestinoActionPerformed
      // TODO add your handling code here:
      if (jcbDepartamentoDestino.isEnabled())
      {
         if (verticeFinal != null && verticeInicio != null)
         {
            if (verticeFinal != verticeInicio)
               DibujarRutas.deseleccionarVertice(jpMapa.getGraphics(), verticeFinal);
         }
         else
         {
            if (verticeFinal != null)
               DibujarRutas.deseleccionarVertice(jpMapa.getGraphics(), verticeFinal);
         }
         
         verticeFinal = grafo.buscarVertice(jcbDepartamentoDestino.getSelectedItem().toString());
         DibujarRutas.seleccionarVertice(jpMapa.getGraphics(), verticeFinal);
      }
   }//GEN-LAST:event_jcbDepartamentoDestinoActionPerformed
/**/
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FramePrincipal().setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtCalcularRuta;
    private javax.swing.JButton jbtMostrarRutas;
    private javax.swing.JComboBox<String> jcbDepartamentoDestino;
    private javax.swing.JComboBox<String> jcbDepartamentoOrigen;
    private javax.swing.JLabel jlbCerrar;
    private javax.swing.JLabel jlbMapa;
    private javax.swing.JPanel jpMapa;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JTextArea jtResultados;
    // End of variables declaration//GEN-END:variables
}
